name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Q08_62 Test 1
      id: q08_62-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q08_62 Test 1
        setup-command: javac Q08_62/*.java
        command: java -cp Q08_62 BattingStatsClient 34 35 30 23 24 32 22 38 26 79
          95 81 100 84 71 70 94 75
        input: ''
        expected-output: "bStat1:\nNumber of players: 9\nHits:\n34 35 30 23 24 32
          22 38 26 \nAt bats:\n79 95 81 100 84 71 70 94 75 \n\nbStat2:\nThe number
          of players is 9\nThe hits for each player are: 34 35 30 23 24 32 22 38 26
          \nThe at-bats for each player are: 79 95 81 100 84 71 70 94 75 \nObjects
          are equal\n\nUsing mutators to change bStat2 data\n\nbStat2:\nNumber of
          players: 9\nHits:\n30 35 30 23 24 32 22 38 26 \nAt bats:\n99 95 81 100 84
          71 70 94 75 \nObjects are not equal\n\nbStat2 batting averages:\n.303 .368
          .370 .230 .286 .451 .314 .404 .347 \n\nbStat2: The total number of hits
          is 260\n\nbStat2: The number of players with a batting average greater than
          .300 is 7\nThe hits are: \n30 35 30 23 24 32 22 38 26 \nThe sorted hits
          are: \n22 23 24 26 30 30 32 35 38 "
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Q08_62 Test 2
      id: q08_62-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q08_62 Test 2
        setup-command: javac Q08_62/*.java
        command: java -cp Q08_62 BattingStatsClient 20 33 35 40 25 15 21 24 36 100
          99 101 100 99 75 88 90 103
        input: ''
        expected-output: "bStat1:\nNumber of players: 9\nHits:\n20 33 35 40 25 15
          21 24 36 \nAt bats:\n100 99 101 100 99 75 88 90 103 \n\nbStat2:\nThe number
          of players is 9\nThe hits for each player are: 20 33 35 40 25 15 21 24 36
          \nThe at-bats for each player are: 100 99 101 100 99 75 88 90 103 \nObjects
          are equal\n\nUsing mutators to change bStat2 data\n\nbStat2:\nNumber of
          players: 9\nHits:\n30 33 35 40 25 15 21 24 36 \nAt bats:\n99 99 101 100
          99 75 88 90 103 \nObjects are not equal\n\nbStat2 batting averages:\n.303
          .333 .347 .400 .253 .200 .239 .267 .350 \n\nbStat2: The total number of
          hits is 259\n\nbStat2: The number of players with a batting average greater
          than .300 is 5\nThe hits are: \n30 33 35 40 25 15 21 24 36 \nThe sorted
          hits are: \n15 21 24 25 30 33 35 36 40 "
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Q08_63 Test 1
      id: q08_63-test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q08_63 Test 1
        setup-command: javac Q08_63/*.java
        command: java -cp Q08_63 GradesClient 31 21 72 81 31 81 32 0 38 74 91
        input: ''
        expected-output: "Setting g1 and g2 arrays to studentGrades\nGrades: 31 21
          72 81 31 81 32 0 38 74 91 \nComparing g1 and g2 for equality\nObjects are
          equal\n\nSorted grades: \n0 21 31 31 32 38 72 74 81 81 91 \nThe highest
          grade is 91\nThe average grade is 50.18\nThe median grade is 38\nThe mode
          is 31"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Q08_63 Test 2
      id: q08_63-test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q08_63 Test 2
        setup-command: javac Q08_63/*.java
        command: java -cp Q08_63 GradesClient 4 15 92 31 42 55 61 78 80 23 99
        input: ''
        expected-output: "Setting g1 and g2 arrays to studentGrades\nGrades: 4 15
          92 31 42 55 61 78 80 23 99 \nComparing g1 and g2 for equality\nObjects are
          equal\n\nSorted grades: \n4 15 23 31 42 55 61 78 80 92 99 \nThe highest
          grade is 99\nThe average grade is 52.73\nThe median grade is 55\nThe mode
          is 4"
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q08_62-TEST-1_RESULTS: "${{steps.q08_62-test-1.outputs.result}}"
        Q08_62-TEST-2_RESULTS: "${{steps.q08_62-test-2.outputs.result}}"
        Q08_63-TEST-1_RESULTS: "${{steps.q08_63-test-1.outputs.result}}"
        Q08_63-TEST-2_RESULTS: "${{steps.q08_63-test-2.outputs.result}}"
      with:
        runners: q08_62-test-1,q08_62-test-2,q08_63-test-1,q08_63-test-2
